openapi: 3.0.0

info:
  title: Todo App API
  version: 0.1.0
  description: Documents the API endpoints for our Todo App

servers:
  - url: http://localhost:4000/
    description: local dev env

paths:
  /user: 
    get:
      tags:
        - User
      description: Test endpoints for User
      responses:
        "200": 
          description: Successfully
          content:
            text/plain:
              schema:
                type: string
